// UI-angular-backup/src/app/pages/informe-page/informe/lista-secciones/lista-secciones.ts
import { Component, WritableSignal, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormGroup, ReactiveFormsModule } from '@angular/forms';
import { SeccionItemComponent } from './seccion-item/seccion-item';
import { Foto } from '../../foto.interface';

@Component({
  selector: 'app-lista-secciones',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, SeccionItemComponent],
  templateUrl: './lista-secciones.html',
})
export class ListaSeccionesComponent {
  seccionesGroups = input<FormGroup[]>([]);
  seccionesColapsadas = input<boolean[]>([]);
  fotosPorSeccionBase64 = input<WritableSignal<Foto[]>[]>([]);

  toggle = output<number>();
  agregarFoto = output<{ event: Event; secIdx: number }>();
  eliminarFoto = output<{ secIdx: number; fotoIdx: number }>();
  descargarFoto = output<Foto>();
  actualizarDescripcion = output<{secIdx: number; fotoIdx: number; descripcion: string}>();

  onAgregarFoto(event: Event, secIdx: number) {
    this.agregarFoto.emit({ event, secIdx });
  }
}

// UI/src/lib/components/informe/ListaSecciones.svelte
<script lang="ts">
  import type { FormState } from '$lib/services/form-initialization.svelte';
  import type { Foto } from '$lib/types/foto.interface';
  import SeccionItem from './SeccionItem.svelte';

  let {
    obraForm,
    seccionesColapsadas,
    fotosPorSeccionBase64,
    toggle,
    agregarFoto,
    eliminarFoto,
    descargarFoto,
    actualizarDescripcion
  }: {
    obraForm: FormState;
    seccionesColapsadas: boolean[];
    fotosPorSeccionBase64: Foto[][];
    toggle: (idx: number) => void;
    agregarFoto: (event: Event, secIdx: number) => void;
    eliminarFoto: (secIdx: number, fotoIdx: number) => void;
    descargarFoto: (foto: Foto) => void;
    actualizarDescripcion: (secIdx: number, fotoIdx: number, descripcion: string) => void;
  } = $props();

</script>

<div class="secciones-container">
  {#if obraForm.secciones.length}
    {#each obraForm.secciones as seccion, idx (idx)}
      <SeccionItem
        {seccion}
        idxSeccion={idx}
        colapsada={seccionesColapsadas[idx]}
        fotos={fotosPorSeccionBase64[idx]}
        onToggle={() => toggle(idx)}
        onAgregarFoto={(event) => agregarFoto(event, idx)}
        onEliminarFoto={(fotoIdx) => eliminarFoto(idx, fotoIdx)}
        onDescargarFoto={descargarFoto}
        onActualizarDescripcion={(fotoIdx, desc) => actualizarDescripcion(idx, fotoIdx, desc)}
      />
    {/each}
  {/if}
</div>
